# Generated by Django 4.2.16 on 2024-09-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_options_remove_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудникиn'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='dolgnost',
            field=models.CharField(max_length=50, verbose_name='Название подразделения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
    ]
