# Generated by Django 4.2.16 on 2024-09-07 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_event_location_event_name_event_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_type',
            name='type',
        ),
        migrations.AddField(
            model_name='event_type',
            name='event_type_name',
            field=models.ManyToManyField(default='', max_length=150, to='forms.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 23, 33, 57, 999996), verbose_name='Дата мероприятия'),
        ),
    ]
