# Generated by Django 4.2.16 on 2024-09-07 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_remove_event_type_type_event_type_event_type_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_type',
            name='event_type_name',
        ),
        migrations.AddField(
            model_name='event_type',
            name='type',
            field=models.CharField(default='', max_length=150, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 23, 39, 20, 759923), verbose_name='Дата мероприятия'),
        ),
    ]
