# Generated by Django 4.2.16 on 2024-09-08 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_event_test_alter_event_date_alter_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 13, 19, 49, 426794), verbose_name='Дата мероприятия'),
        ),
        migrations.AlterField(
            model_name='event_type',
            name='type',
            field=models.CharField(choices=[(1, 'One'), (2, 'Two')], max_length=150),
        ),
    ]
