# Generated by Django 4.2.16 on 2024-09-08 13:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_alter_event_date_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 13, 44, 9, 433387), verbose_name='Дата мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='decor',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], default='yes', max_length=150, verbose_name='Декорация'),
        ),
        migrations.AlterField(
            model_name='event',
            name='grim',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], default='yes', max_length=150, verbose_name='Грим'),
        ),
        migrations.AlterField(
            model_name='event',
            name='kostum',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], default='yes', max_length=150, verbose_name='Костюм'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.event_location', verbose_name='Место проведения мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.event_name', verbose_name='Название мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rekvizit',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], default='yes', max_length=150, verbose_name='Реквизит'),
        ),
        migrations.AlterField(
            model_name='event',
            name='svet',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], default='yes', max_length=150, verbose_name='Свет'),
        ),
        migrations.AlterField(
            model_name='event',
            name='utochneniya',
            field=models.TextField(max_length=150, verbose_name='Реквизит'),
        ),
        migrations.AlterField(
            model_name='event',
            name='video',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], default='yes', max_length=150, verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='event',
            name='zvuk',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], default='yes', max_length=150, verbose_name='Звук'),
        ),
        migrations.AlterField(
            model_name='event_name',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='Название'),
        ),
    ]
