# Generated by Django 4.2.16 on 2024-09-08 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_alter_event_date_alter_event_utochneniya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 13, 54, 11, 227875), verbose_name='Дата мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='decor',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=150, verbose_name='Декорация'),
        ),
        migrations.AlterField(
            model_name='event',
            name='grim',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=150, verbose_name='Грим'),
        ),
        migrations.AlterField(
            model_name='event',
            name='kostum',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=150, verbose_name='Костюм'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rekvizit',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=150, verbose_name='Реквизит'),
        ),
        migrations.AlterField(
            model_name='event',
            name='svet',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=150, verbose_name='Свет'),
        ),
        migrations.AlterField(
            model_name='event',
            name='video',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=150, verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='event',
            name='zvuk',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=150, verbose_name='Звук'),
        ),
    ]
