# Generated by Django 4.2.16 on 2024-09-08 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_alter_event_date_alter_event_decor_alter_event_grim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 16, 28, 41, 531878), verbose_name='Дата мероприятия'),
        ),
    ]
