# Generated by Django 4.2.16 on 2024-10-01 12:42

import colorfield.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0026_alter_event_date_alter_event_type_button_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 1, 12, 42, 28, 289327), verbose_name='Дата мероприятия'),
        ),
        migrations.AlterField(
            model_name='event_type',
            name='button_color',
            field=colorfield.fields.ColorField(default='#000', image_field=None, max_length=25, samples=None, verbose_name='Цвет кнопки'),
        ),
    ]
