# Generated by Django 4.2.16 on 2024-10-02 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0028_alter_event_date_alter_event_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 2, 14, 58, 3, 357930), verbose_name='Дата мероприятия'),
        ),
    ]
