# Generated by Django 4.2.16 on 2024-11-08 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0039_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 8, 11, 4, 27, 469972), verbose_name='Дата мероприятия'),
        ),
    ]
