# Generated by Django 4.2.16 on 2024-09-08 13:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.event_type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 13, 17, 17, 33026), verbose_name='Дата мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[], default='Спектакль', max_length=150, verbose_name='Тип мероприятия'),
        ),
        migrations.AlterField(
            model_name='event_type',
            name='type',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two')]),
        ),
    ]
