# Generated by Django 4.2.16 on 2024-09-08 13:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_alter_event_date_alter_event_type_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='test',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 13, 27, 59, 143154), verbose_name='Дата мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.event_type'),
        ),
    ]
