# Generated by Django 4.2.16 on 2024-09-30 23:01

import colorfield.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0024_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_type',
            name='button_color',
            field=colorfield.fields.ColorField(default='#000', image_field=None, max_length=25, samples=None, verbose_name='Цвет кнопки'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 30, 23, 1, 51, 4883), verbose_name='Дата мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='utochneniya',
            field=models.TextField(blank=True, max_length=150, verbose_name='Уточнения'),
        ),
    ]
