# Generated by Django 4.2.16 on 2024-10-01 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0025_event_type_button_color_alter_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 1, 12, 40, 53, 579231), verbose_name='Дата мероприятия'),
        ),
        migrations.AlterField(
            model_name='event_type',
            name='button_color',
            field=models.CharField(default='#000', max_length=10, verbose_name='Цвет кнопки'),
        ),
    ]
