# Generated by Django 4.2.16 on 2024-10-01 14:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0027_alter_event_date_alter_event_type_button_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 1, 14, 39, 22, 632), verbose_name='Дата мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='forms.event_location', verbose_name='Место проведения мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='forms.event_type', verbose_name='Тип мероприятия'),
        ),
    ]
