# Generated by Django 4.2.16 on 2024-11-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_spect_length_alter_spect_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spect',
            name='video',
            field=models.FileField(blank=True, default='', upload_to='materials/<django.db.models.fields.CharField>/video/', verbose_name='Видео спектакля'),
        ),
    ]
