# Generated by Django 4.2.16 on 2024-11-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_spect_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spect',
            name='video',
            field=models.FileField(blank=True, default='', upload_to='materials/Название спектакля/video/', verbose_name='Видео спектакля'),
        ),
    ]
