# Generated by Django 4.2.16 on 2024-11-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_spect_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spect',
            name='decor_doc',
            field=models.FileField(blank=True, default='', upload_to='materials/valera/decor_doc/', verbose_name='Декорация'),
        ),
        migrations.AlterField(
            model_name='spect',
            name='grim_doc',
            field=models.FileField(blank=True, default='', upload_to='materials/valera/grim_doc/', verbose_name='Грим'),
        ),
        migrations.AlterField(
            model_name='spect',
            name='kostum_doc',
            field=models.FileField(blank=True, default='', upload_to='materials/valera/kostum_doc/', verbose_name='Костюм'),
        ),
        migrations.AlterField(
            model_name='spect',
            name='rekv_doc',
            field=models.FileField(blank=True, default='', upload_to='materials/valera/rekv_doc/', verbose_name='Реквизит'),
        ),
        migrations.AlterField(
            model_name='spect',
            name='svet_doc',
            field=models.FileField(blank=True, default='', upload_to='materials/valera/svet_doc/', verbose_name='Свет'),
        ),
        migrations.AlterField(
            model_name='spect',
            name='video',
            field=models.FileField(blank=True, default='', upload_to='materials/valera/video/', verbose_name='Видео спектакля'),
        ),
        migrations.AlterField(
            model_name='spect',
            name='video_doc',
            field=models.FileField(blank=True, default='', upload_to='materials/valera/video_doc/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='spect',
            name='zvuk_doc',
            field=models.FileField(blank=True, default='', upload_to='materials/valera/zvuk_doc/', verbose_name='Звук'),
        ),
    ]
