# Generated by Django 4.2.16 on 2024-11-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_spect_decor_doc_alter_spect_grim_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spect',
            name='video',
            field=models.CharField(blank=True, default='', max_length=5000, verbose_name='Видео спектакля'),
        ),
    ]
